### ISSUE TITLE
Grid component 🛠

### ISSUE THREAD

**Issue by Noorani-MM** [xaankoow/segmento-nuxt#12]
## The suggestion 📝

A grid component to make us faster to implement these tables. ( [Figma link](https://www.figma.com/file/CBlIO1l0IbroPynLUb09GV/Rank-Tracker-Project?node-id=0%3A1&mode=dev) you can find it on `تب رقبا` section )

## Description 📚

- Component must create on `components/Grid/index.vue`

example: 

```html
<div class="grid [other styles]">
     <slot></slot>
</div>
```

On slot tag will fill with 

```html
<div> // content </div>
<div> // content </div>
<div> // content </div>

<!-- etc ... -->

```

## Necessary files

![image](https://github.com/xaankoow/segmento-nuxt/assets/74505328/7d8e2ee0-d1b1-4ae3-9390-d1bce8f466fa)

**Comment by Javad-Ashrafi** [comment]
for solution 1 Is there a special format for input data or props?
and in solution 2, the component must already be created, right?

**Comment by Noorani-MM** [comment]
> for solution 1 Is there a special format for input data or props? and in solution 2, the component must already be created, right?

- In the first solution, if you want to receive a property, you need to specify the data type of the parameter and indicate whether it is required or not. However, having a default value is optional.

for example:

```javascript

<script setup>
const props = defineProps({
   bordered: {
       type: Boolean,
       default: false,
   },
   gap: {
       type: Number,
       required: true,
   },
   color: {
       type: String,
       required: false,
   }
});
</script>
```

- For the second solution, it is not necessary to create a component. Creating a CSS class named "table" and providing the necessary styles for the entire table within this class would suffice.

for example:

```css
.table {
   /** base table style 
}

.table tr {
   /** table rows style **/
}
```

**The preference is to style using Tailwind CSS for the second solution.**
