### ISSUE TITLE
An update on popup component 🛠

### ISSUE THREAD

**Issue by Xaankoo-Noyan** [xaankoow/segmento-nuxt#43]
## The suggestion 📝

- As a base component, the popup have be a customizable and dynamic component. So here we go!

## Description 📚

According to the last version of the component, there is nothing to customize except the content. So we need an update:

- Receive these as **Property (prop)**:
    - `bubble_bursting`: Specify that the popup get terminate if client clicked out of the content box or not!
        - type: `bool`
        - default: `true`
    - `parent_element`: Specify the element selector that is getting locked on scroll and *gray sheet*.
        - type: `str`
        - default: `body` as a html tag.
    - `opacity`: Specify percentage of the gray sheet opacity (it is because of the contents that are behind it):
        - type: `int` between 1 and 100
        - default: `50`
    
- Receive these as components:
    - `content`: Specify the *HTML* content that is displaying in popup.

If there was any question, reply and write a comment.

**Comment by Noorani-MM** [comment]
This issue closed by #54
